basePath: /v1
definitions:
  main.CreatePhotoCommentRequestPayload:
    properties:
      content:
        type: string
      userID:
        type: integer
    required:
    - content
    - userID
    type: object
  main.CreatePhotoCommentResponsePayload:
    properties:
      created:
        type: boolean
    type: object
  main.CreateVideoCommentRequestPayload:
    properties:
      content:
        type: string
      userID:
        type: integer
    required:
    - content
    - userID
    type: object
  main.CreateVideoCommentResponsePayload:
    properties:
      created:
        type: boolean
    type: object
  main.LoginUserRequestPayload:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  main.LogoutRequestPayload:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  main.PhotoCommentResponsePayload:
    properties:
      content:
        type: string
      created_at:
        type: string
      username:
        type: string
    type: object
  main.PhotoPostItem:
    properties:
      id:
        type: integer
      landscape:
        type: string
      large:
        type: string
      large2x:
        type: string
      medium:
        type: string
      original:
        type: string
      photographer:
        type: string
      portrait:
        type: string
      small:
        type: string
      tiny:
        type: string
    type: object
  main.PhotoPostResponsePayload:
    properties:
      next_page:
        type: integer
      photo_items:
        items:
          $ref: '#/definitions/main.PhotoPostItem'
        type: array
    type: object
  main.RefreshTokenRequestPayload:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  main.RefreshTokenResponsePayload:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
    type: object
  main.RegisterUserRequestPayload:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 5
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - username
    type: object
  main.TokenResponsePayload:
    properties:
      token:
        type: string
    type: object
  main.VerifyUserRequestPayload:
    properties:
      code:
        type: string
      email:
        maxLength: 255
        type: string
      token:
        type: string
    required:
    - code
    - email
    - token
    type: object
  main.VerifyUserResponsePayload:
    properties:
      status:
        type: string
    type: object
  main.VideoCommentResponsePayload:
    properties:
      content:
        type: string
      created_at:
        type: string
      username:
        type: string
    required:
    - content
    - created_at
    - username
    type: object
  main.VideoDownloadFile:
    properties:
      video_link:
        type: string
      video_size:
        type: integer
    type: object
  main.VideoPostResponsePayload:
    properties:
      duration:
        type: integer
      id:
        type: integer
      video_files:
        items:
          $ref: '#/definitions/main.VideoDownloadFile'
        type: array
      video_url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for MiGalaria, an application for pictures and short videos.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MiGalaria API
paths:
  /authentication/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User login credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.LoginUserRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: User token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: User login
      tags:
      - authentication
  /authentication/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token to revoke
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.LogoutRequestPayload'
      produces:
      - application/json
      responses:
        "204":
          description: No content
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Logout user
      tags:
      - authentication
  /authentication/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.RefreshTokenRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: New access token
          schema:
            $ref: '#/definitions/main.RefreshTokenResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Refresh access token
      tags:
      - authentication
  /authentication/register:
    post:
      consumes:
      - application/json
      description: Registers a user
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.RegisterUserRequestPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User registered
          schema:
            $ref: '#/definitions/main.TokenResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Registers a user
      tags:
      - authentication
  /authentication/verify:
    post:
      consumes:
      - application/json
      description: verify user
      parameters:
      - description: User verification credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.VerifyUserRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: User verified
          schema:
            $ref: '#/definitions/main.VerifyUserResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: User verification
      tags:
      - authentication
  /health:
    get:
      description: Healthcheck endpoint
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Healthcheck
      tags:
      - ops
  /photos:
    get:
      consumes:
      - application/json
      description: Get all photo posts
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PhotoPostResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get all photo posts
      tags:
      - photos
  /photos/{postID}/comments:
    get:
      consumes:
      - application/json
      description: Get all comments using a postID
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.PhotoCommentResponsePayload'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get all comments using a postID
      tags:
      - photos
  /photos/{postID}/create-comment:
    post:
      consumes:
      - application/json
      description: Create comment for a photo post
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      - description: Comment
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.CreatePhotoCommentRequestPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Comment created
          schema:
            $ref: '#/definitions/main.CreatePhotoCommentResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create comment for a photo post
      tags:
      - photos
  /videos:
    get:
      consumes:
      - application/json
      description: Get all video posts
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.VideoPostResponsePayload'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get all video posts
      tags:
      - videos
  /videos/{postID}/comments:
    get:
      consumes:
      - application/json
      description: Get all comments using a postID
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.VideoCommentResponsePayload'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get all comments using a postID
      tags:
      - videos
  /videos/{postID}/create-comment:
    post:
      consumes:
      - application/json
      description: Create comment for a video post
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      - description: Comment
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.CreateVideoCommentRequestPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Comment created
          schema:
            $ref: '#/definitions/main.CreateVideoCommentResponsePayload'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create comment for a video post
      tags:
      - videos
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
